# Tap's

# Brew's

brew "git"
brew "jj"
brew "python@3.14"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "colima"
brew "docker"
brew "docker-compose"
brew "mas"

# Cask's

cask "anki"
cask "ghostty"
cask "git-credential-manager"
cask "rectangle"
cask "visual-studio-code"
cask "tailscale-app"
cask "syncthing-app"
cask "aldente"

# MAC Store Apps

mas "Amphetamine", id: 937984704
